site_name: "nelpy"
repo_name: nelpy/nelpy
repo_url: https://github.com/nelpy/nelpy
edit_uri: edit/master/docs/

extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  palette:
  - media: "(prefers-color-scheme: dark)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: light
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - content.tabs.link
  - navigation.footer
  - navigation.indexes
  - navigation.instant.prefetch
  - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.suggest
  - toc.follow

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
    - docs/copy_tutorials.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: ["nelpy/"]
        options:
          docstring_style: numpy
          docstring_section_style: table
          filters: ["!__", "!^_"] # exclude all members starting with __
- include-markdown:  # https://github.com/mondeja/mkdocs-include-markdown-plugin
    opening_tag: "{%"
    closing_tag: "%}"
    rewrite_relative_urls: true
    heading_offset: 1
- mkdocs-jupyter:
    include: ["*.ipynb"]
    include_source: true
    ignore_h1_titles: true
    execute: false
    allow_errors: true
    include_requirejs: true
- minify:
    minify_html: true
    minify_js: true
    minify_css: true
    htmlmin_opts:
      remove_comments: true
    cache_safe: true

nav:
- Home: index.md
- API Reference: reference/
- Tutorials:
  - AnalogSignalArray Tutorial: tutorials/AnalogSignalArrayTutorial.ipynb
  - EpochArray Tutorial: tutorials/EpochArrayTutorial.ipynb
  - Linear Track Demo: tutorials/LinearTrackDemo.ipynb
  - SpikeTrain Smoothing: tutorials/SpikeTrainSmoothing.ipynb
  - plotting: tutorials/plotting.ipynb
  - WMaze Demo: tutorials/WMazeDemo.ipynb
  - Backyard Brains EEG: tutorials/BackyardBrainsEEG.ipynb
  - develop: tutorials/develop.ipynb
